- name: install and run nginx
  hosts: web
  vars_prompt:
    - name: ansible_user
      prompt: "Enter SSH username"
      private: no
    - name: ansible_password
      prompt: "Enter SSH password"
      private: yes
  become: yes # equal to -b in adhoc commands, getting root access
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
